"""add triage_log and planned_events

Revision ID: 002
Revises: 001
Create Date: 2026-06-17 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planned_events',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('event_cause', sa.String(length=50), nullable=False),
    sa.Column('corridor', sa.String(length=100), nullable=True),
    sa.Column('junction', sa.String(length=100), nullable=True),
    sa.Column('police_station', sa.String(length=100), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requires_road_closure', sa.Boolean(), nullable=True),
    sa.Column('duration_mins', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triage_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('corridor', sa.String(length=100), nullable=True),
    sa.Column('event_cause', sa.String(length=50), nullable=True),
    sa.Column('vehicle_type', sa.String(length=30), nullable=True),
    sa.Column('hour_of_day', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('closure_probability', sa.Float(), nullable=True),
    sa.Column('priority_probability', sa.Float(), nullable=True),
    sa.Column('predicted_priority', sa.String(length=10), nullable=True),
    sa.Column('disagreement_flag', sa.Boolean(), nullable=True),
    sa.Column('predicted_duration_mins', sa.Float(), nullable=True),
    sa.Column('recommended_station', sa.String(length=100), nullable=True),
    sa.Column('recommended_officer_count', sa.Integer(), nullable=True),
    sa.Column('escalation_tier', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triage_log')
    op.drop_table('planned_events')
    # ### end Alembic commands ###
